### ISSUE TITLE
Highlight scss vars

### ISSUE THREAD

**Issue by tylerfowle** [neoclide/coc-highlight#9]
Highlight scss variables that are defined as colors.  Currently only the variable declaration is highlighted, but the variable doesnt highlight when used.

```scss

// these are highlighted
$color1: red;
$color2: blue;
$color3: #345612;
$color4: #8833ca;

ul {
  // these are not highlighted
  background: $color1;
  color: $color2;

  li {
    // these are not highlighted
    color: $color3;
    background: $color4;
  }
}
```
